// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nass.Data;

#nullable disable

namespace Nass.Migrations
{
    [DbContext(typeof(NassadContext))]
    [Migration("20251228174513_MyMigration5")]
    partial class MyMigration5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nass.Models.Agencies", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgencyId"));

                    b.Property<string>("AgencyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AgencyJoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("AgencyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgencyStatus")
                        .HasColumnType("int");

                    b.Property<string>("AgencyTaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyTenet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AgencyUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgencyUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgencyId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("Nass.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Nass.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CustomerJoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CustomerLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomerTaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerTenet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Nass.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trans_Id")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("Trans_Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Nass.Models.NotificationRecipient", b =>
                {
                    b.Property<int>("NotificationRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationRecipientId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trans_id")
                        .HasColumnType("int");

                    b.HasKey("NotificationRecipientId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("Trans_id");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("Trans_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trans_id"));

                    b.Property<int?>("Agency_id")
                        .HasColumnType("int");

                    b.Property<string>("Agency_tenat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int");

                    b.Property<int>("TransStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Trans_categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Trans_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Trans_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Trans_uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Trans_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("trans_recived_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Trans_id");

                    b.HasIndex("Agency_id");

                    b.HasIndex("Customer_id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Nass.Models.Notification", b =>
                {
                    b.HasOne("Transaction", "Transaction")
                        .WithMany("NotificationList")
                        .HasForeignKey("Trans_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Nass.Models.NotificationRecipient", b =>
                {
                    b.HasOne("Nass.Models.Agencies", "Agency")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nass.Models.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transaction", "Transaction")
                        .WithMany("Notifications")
                        .HasForeignKey("Trans_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Notification");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("Nass.Models.Agencies", "Agency")
                        .WithMany("Transactions")
                        .HasForeignKey("Agency_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nass.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Nass.Models.Agencies", b =>
                {
                    b.Navigation("NotificationRecipients");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Nass.Models.Customer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Nass.Models.Notification", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Navigation("NotificationList");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
