// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nass.Models;

#nullable disable

namespace Nass.Migrations
{
    [DbContext(typeof(NassadContext))]
    [Migration("20251216180029_InitialCreatew1")]
    partial class InitialCreatew1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nass.Models.Agency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Agency_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgencyId"));

                    b.Property<string>("AgencyAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Agency_address");

                    b.Property<string>("AgencyEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Agency_email");

                    b.Property<DateTime>("AgencyJoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Agency_joined_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("AgencyLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Agency_location");

                    b.Property<string>("AgencyLogo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Agency_logo");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Agency_name");

                    b.Property<string>("AgencyPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Agency_password");

                    b.Property<string>("AgencyPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Agency_phone");

                    b.Property<string>("AgencyTaxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Agency_tax_id");

                    b.Property<string>("AgencyTenet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Agency_tenet");

                    b.Property<Guid>("AgencyUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Agency_uid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AgencyUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Agency_username");

                    b.Property<string>("AgencyWebsite")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Agency_website");

                    b.HasKey("AgencyId")
                        .HasName("PK__Agency__754F0F7CF043303F");

                    b.ToTable("Agency", (string)null);
                });

            modelBuilder.Entity("Nass.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B80DCF49B");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Nass.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("customer_address");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_email");

                    b.Property<DateTime>("CustomerJoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("customer_joined_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("CustomerLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_location");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_password");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("customer_phone");

                    b.Property<string>("CustomerTaxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_tax_id");

                    b.Property<string>("CustomerTenet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("customer_tenet");

                    b.Property<Guid>("CustomerUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Customer_uid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CustomerUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_username");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__CD65CB85E53A9F05");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Trans_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransId"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int")
                        .HasColumnName("Agency_id");

                    b.Property<string>("AgencyTenat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Agency_tenat");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<byte[]>("TransBlobAttachmenet")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Trans_blob_attachmenet");

                    b.Property<string>("TransCategories")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Trans_categories");

                    b.Property<DateTime>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Trans_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("TransDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Trans_description");

                    b.Property<int>("TransMaxAgency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Trans_max_agency");

                    b.Property<DateTime?>("TransRecivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("trans_recived_date");

                    b.Property<string>("TransStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("Trans_status");

                    b.Property<Guid>("TransUid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Trans_uid")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("TransUrlAttachment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Trans_url_attachment");

                    b.HasKey("TransId")
                        .HasName("PK__Transact__7B18403588279D35");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("Nass.Models.Agency", "Agency")
                        .WithMany("Transactions")
                        .HasForeignKey("AgencyId")
                        .HasConstraintName("FK_Transactions_Agency");

                    b.HasOne("Nass.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Customer");

                    b.Navigation("Agency");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Nass.Models.Agency", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Nass.Models.Customer", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
